Repository Bridgeconn/VachanOnline-v2, pull requests merged in 2021-11, with the labels that each got.

#140 Fixed issue #116 notes refresh, bookmarks
  src/components/highlight/FetchHighlights.js
  src/components/note/GetChapterNotes.js
Labels: bug

#120 added docker, need to add docker-compose
  .dockerignore
  Dockerfile
Labels: DevOps CR

#141 Justify chapter print text
  src/components/read/Bible.js
Labels: bug

#143 1.3.2 Release
  package-lock.json
  package.json
  src/components/common/Metadata.js
  src/components/common/utillity.js
  src/components/highlight/FetchHighlights.js
  src/components/infographics/Infographics.js
  src/components/landing/AboutUs.js
  src/components/note/GetChapterNotes.js
  src/components/note/Note.js
  src/components/read/Bible.js
  src/components/read/BiblePane.js
  src/components/read/MenuBar.js
  src/components/read/ReadBible.js
  src/components/read/Setting.js
  src/components/readingplans/Readingplans.js
  src/components/stories/Stories.js
Labels: release
