Repository Bridgeconn/VachanOnline-v2, pull requests merged in 2022-06, with the labels that each got.

#188 Hide verse label
  package-lock.json
  src/components/bookmark/Bookmarks.js
  src/components/commentary/Commentary.js
  src/components/common/Metadata.js
  src/components/common/Version.js
  src/components/common/utility.js
  src/components/dictionary/Dictionary.js
  src/components/highlight/Highlights.js
  src/components/infographics/Infographics.js
  src/components/landing/Landing.js
  src/components/note/Notes.js
  src/components/read/MenuBar.js
  src/components/read/ReadBible.js
  src/components/search/Search.js
  src/store/reducer.js
Labels: cosmetic

#189 fixed #178
  src/components/common/Version.js
Labels: bug

#194 added code to display farsi in rtl & removed link for legacy site
  src/components/landing/PageHeader.js
  src/components/read/TopBar.js
  src/components/stories/Stories.js
Labels: enhancement, cosmetic
