Repository Bridgeconn/VachanOnline-v2, pull requests merged in 2022-07, with the labels that each got.

#201 Fixed VO #122
  src/components/bookmark/Bookmarks.js
  src/components/highlight/Highlights.js
  src/components/note/Notes.js
Labels: bug, medium priority

#203 Added language dropdown in video panel
  src/components/audio/Audio.js
  src/components/common/utility.js
  src/components/read/ReadBible.js
  src/components/video/Video.js
Labels: enhancement

#206 fixed scroll in obs #139
  src/components/stories/Stories.js
Labels: Usability

#208 Add language drop down in infographics #164
  src/components/common/Version.js
  src/components/common/utility.js
  src/components/infographics/Infographics.js
  src/components/read/ReadBible.js
Labels: enhancement
