Repository Bridgeconn/VachanOnline-v2, pull requests merged in 2023-06, with the labels that each got.

#347 Added Tooltip for Print #338
  src/components/read/MenuBar.js
Labels: cosmetic

#357 Bug fixed for retaining last selected lang #355
  src/components/commentary/Commentary.js
  src/components/commentary/CommentaryCombo.js
Labels: bug

#361 Highlighted selected language & version #339
  src/components/common/Version.js
Labels: enhancement, Usability

#370 Moved bottom icons higher on the landing page#365
  src/components/landing/Banner.js
  src/components/landing/BibleIndex.js
  src/components/landing/ImageCard.js
  src/components/landing/Landing.js
Labels: UX

#378 keep prev and next arrow in top in parallel bible page of mobile view #363
  src/components/read/Bible.js
Labels: enhancement, Mobile Browser

#371 Changed Reading plan -Tool tip positioning #123
  src/components/readingplan/ReadingPlan.js
Labels: enhancement, Usability

#380 Updated release notes v1.4.2 in about us page
  src/components/landing/AboutUs.js
Labels: release

#381 v1.4.2 release merge dev to master
  src/components/audio/Audio.js
  src/components/commentary/Commentary.js
  src/components/commentary/CommentaryCombo.js
  src/components/common/BigTooltip.js
  src/components/common/BookCombo.js
  src/components/common/Version.js
  src/components/common/utility.js
  src/components/landing/AboutUs.js
  src/components/landing/Banner.js
  src/components/landing/BibleIndex.js
  src/components/landing/ImageCard.js
  src/components/landing/LanguageBar.js
  src/components/read/Bible.js
  src/components/read/MenuBar.js
  src/store/bibleData.js
  src/store/colorCode.js
  src/store/languageData.js
  src/store/reducer.js
Labels: release

#373 version highlighted in commentary dropdown #372
  src/components/commentary/CommentaryCombo.js
  src/components/common/Version.js
  src/components/read/Bible.js
Labels: enhancement

#384 Bible lang dropdown retain last selected lang #377
  src/components/common/Version.js
Labels: bug

#386 Added ISL Book dropdown in mobile view #218
  src/components/signbible/SignBible.js
Labels: enhancement, UX
