Repository Bridgeconn/VachanOnline-v2, pull requests merged in 2023-04, with the labels that each got.

#293 #258 Language not setting in infographics
  src/components/signbible/SignBible.js
Labels: bug

#295 update npm packages using npm audit fix
  package-lock.json
Labels: package update

#249 Browser Mobile view
  package-lock.json
  package.json
  src/components/Drawer/Drawer.js
  src/components/audio/Audio.js
  src/components/bookmark/Bookmarks.js
  src/components/commentary/Commentary.js
  src/components/commentary/CommentaryCombo.js
  src/components/common/BookCombo.js
  src/components/common/PrintBox.js
  src/components/common/Version.js
  src/components/common/utility.js
  src/components/dictionary/Dictionary.js
  src/components/dictionary/DictionaryCombo.js
  src/components/dictionary/DictionaryWordCombo.js
  src/components/highlight/Highlight.js
  src/components/highlight/Highlights.js
  src/components/infographics/Infographics.js
  src/components/landing/BibleIndex.js
  src/components/landing/Landing.js
  src/components/landing/LandingFooter.js
  src/components/landing/PageHeader.js
  src/components/login/Login.js
  src/components/login/LoginMenu.js
  src/components/note/Note.js
  src/components/note/Notes.js
  src/components/read/Bible.js
  src/components/read/BiblePane.js
  src/components/read/BottomBar.js
  src/components/read/BottomToolBar.js
  src/components/read/MenuBar.js
  src/components/read/MenuItem.js
  src/components/read/ReadBible.js
  src/components/read/Setting.js
  src/components/read/TopBar.js
  src/components/readingplan/ReadingPlan.js
  src/components/search/Search.js
  src/components/signbible/SignBible.js
  src/components/video/Video.js
  src/index.css
  src/store/colorCode.js
  src/store/reducer.js
  src/store/views.js
Labels: enhancement

#299 Mobile view
  package-lock.json
  package.json
  src/components/audio/Audio.js
  src/components/bookmark/Bookmarks.js
  src/components/commentary/Commentary.js
  src/components/commentary/CommentaryCombo.js
  src/components/common/BookCombo.js
  src/components/common/Metadata.js
  src/components/common/PrintBox.js
  src/components/common/Version.js
  src/components/common/utility.js
  src/components/dictionary/Dictionary.js
  src/components/dictionary/DictionaryCombo.js
  src/components/dictionary/DictionaryWordCombo.js
  src/components/highlight/Highlight.js
  src/components/highlight/Highlights.js
  src/components/infographics/Infographics.js
  src/components/landing/BibleIndex.js
  src/components/landing/Landing.js
  src/components/landing/LandingFooter.js
  src/components/landing/PageHeader.js
  src/components/login/Login.js
  src/components/login/LoginMenu.js
  src/components/note/Note.js
  src/components/note/Notes.js
  src/components/read/Bible.js
  src/components/read/BiblePane.js
  src/components/read/BottomBar.js
  src/components/read/BottomToolBar.js
  src/components/read/MenuBar.js
  src/components/read/MenuItem.js
  src/components/read/ReadBible.js
  src/components/read/Setting.js
  src/components/read/SideDrawer.js
  src/components/read/TopBar.js
  src/components/readingplan/ReadingPlan.js
  src/components/search/Search.js
  src/components/signbible/SignBible.js
  src/components/stories/Stories.js
  src/components/video/Video.js
  src/index.css
  src/store/colorCode.js
  src/store/reducer.js
  src/store/views.js
Labels: Mobile Browser
