Repository Bridgeconn/VachanOnline-v2, pull requests merged in 2023-09, with the labels that each got.

#431 Search passage in read mode #367
  src/components/common/BookCombo.js
  src/components/common/Version.js
  src/components/common/utility.js
  src/components/landing/BibleIndex.js
  src/components/read/Bible.js
  src/components/read/BiblePane.js
  src/components/read/MenuBar.js
  src/components/read/TopBar.js
  src/components/search/SearchPassage.js
  src/store/reducer.js
Labels: enhancement

#433 #294 updated packages also remove unused packages
  package-lock.json
  package.json
  src/components/login/Login.js
  src/components/login/LoginMenu.js
  src/firebase/initFirebase.js
  src/index.js
Labels: dependencies, package update

#442 Correction as per QA comments
  docs/desktop/docs/about.md
  docs/desktop/docs/bibleStories.mdx
  docs/desktop/docs/bookmarks.md
  docs/desktop/docs/commentaries.mdx
  docs/desktop/docs/dictionaries.md
  docs/desktop/docs/infographics.mdx
  docs/desktop/docs/readBible.mdx
  docs/desktop/docs/searchBible.md
  docs/desktop/docs/signLanguageBible.mdx
  docs/desktop/docs/studyBible.mdx
  docs/desktop/docs/websiteNavigation.md
Labels: Documentation

#445 Desktop user manual#286
  docs/desktop/docs/searchBible.md
  docs/desktop/docs/signLanguageBible.mdx
Labels: Documentation

#444 Language version bug fix#423
  src/components/common/Version.js
  src/components/landing/BibleIndex.js
Labels: bug

#446 Audio nagamese bugfix#424
  src/components/common/BookCombo.js
  src/components/login/Login.js
  src/components/note/Notes.js
  src/components/read/SideDrawer.js
  src/components/read/StudyBible.js
  src/components/read/TopBar.js
  src/store/views.js
Labels: bug

#450 Read mode search passage2#436
  src/components/common/Version.js
  src/components/common/utility.js
  src/components/read/Bible.js
  src/components/read/BiblePane.js
Labels: enhancement
