Repository Bridgeconn/VachanOnline-v2, pull requests merged in 2023-11, with the labels that each got.

#481 Deploy language data file separately#467
  src/components/common/Version.js
  src/components/common/utility.js
  src/store/api.js
  src/store/reducer.js
Labels: operational change request

#483 Book dropdown Issue fixed for minority lang #400
  src/components/video/Video.js
Labels: enhancement, SP2, FB1, SP3

#498 Release v1.7.0 dev to master PR
  package-lock.json
  package.json
  public/locales/en/translation.json
  public/locales/hi/translation.json
  src/App.js
  src/components/audio/Audio.js
  src/components/audio/AudioBible.js
  src/components/audio/AudioCombo.js
  src/components/bookmark/Bookmark.js
  src/components/bookmark/Bookmarks.js
  src/components/commentary/Commentary.js
  src/components/common/BookCombo.js
  src/components/common/Close.js
  src/components/common/Metadata.js
  src/components/common/MultiLanguageDropdown.js
  src/components/common/Player.js
  src/components/common/PrintBox.js
  src/components/common/Setting.js
  src/components/common/Version.js
  src/components/common/VideoCard.js
  src/components/common/images/screenshot.jpg
  src/components/common/utility.js
  src/components/dictionary/Dictionary.js
  src/components/highlight/Highlight.js
  src/components/highlight/Highlights.js
  src/components/infographics/Infographics.js
  src/components/landing/AboutUs.js
  src/components/landing/BibleIndex.js
  src/components/landing/ImageCard.js
  src/components/landing/Landing.js
  src/components/landing/LandingFooter.js
  src/components/landing/LanguageBar.js
  src/components/landing/PageHeader.js
  src/components/login/Login.js
  src/components/login/LoginMenu.js
  src/components/note/Note.js
  src/components/note/Notes.js
  src/components/read/Bible.js
  src/components/read/BibleMenu.js
  src/components/read/BiblePane.js
  src/components/read/BottomBar.js
  src/components/read/MenuBar.js
  src/components/read/ReadBible.js
  src/components/read/Setting.js
  src/components/read/SideDrawer.js
  src/components/read/StudyBible.js
  src/components/read/TopBar.js
  src/components/readingplan/ReadingPlan.js
  src/components/search/Search.js
  src/components/search/SearchPassage.js
  src/components/signbible/SignBible.js
  src/components/songs/Songs.js
  src/components/stories/Stories.js
  src/components/video/Video.js
  src/i18n.js
  src/store/api.js
  src/store/languageData.js
  src/store/reducer.js
Labels: release
