Repository Bridgeconn/VachanOnline-v2, pull requests merged in 2023-08, with the labels that each got.

#403 Added description for ISL Video #389
  src/components/signbible/SignBible.js
  src/components/signbible/VideoCard.js
Labels: enhancement

#407 #396 Selected version language not highlighted mobile
  src/components/common/Version.js
Labels: bug

#408 Isl video des #389
  src/components/signbible/VideoCard.js
Labels: enhancement

#401 Read bible mode #149
  package-lock.json
  package.json
  src/App.js
  src/components/audio/Audio.js
  src/components/common/BookCombo.js
  src/components/common/Version.js
  src/components/common/utility.js
  src/components/landing/BibleIndex.js
  src/components/landing/ImageCard.js
  src/components/landing/Landing.js
  src/components/landing/LanguageBar.js
  src/components/landing/PageHeader.js
  src/components/read/MenuBar.js
  src/components/read/ReadBible.js
  src/components/read/StudyBible.js
  src/components/read/TopBar.js
  src/components/signbible/SignBible.js
Labels: enhancement

#421 Added null check, found content related issue #415
  src/components/commentary/CommentaryCombo.js
Labels: bug

#425 v1.5.1 patch release
  src/components/commentary/CommentaryCombo.js
  src/components/common/BookCombo.js
  src/components/landing/Landing.js
Labels: release
