Repository Bridgeconn/VachanOnline-v2, pull requests merged in 2024-01, with the labels that each got.

#542 P q usfm tag#296
  src/components/common/utility.js
  src/components/read/Bible.js
  src/store/usfm.js
Labels: enhancement

#543 fixed issue with merged verses missing
  src/components/read/Bible.js
Labels: bug

#549 Fixed the bug Songs title is not changing to the selected multi language #546
  src/components/songs/Songs.js
Labels: bug

#558 updated code to search local language refs
  src/components/common/utility.js
Labels: bug

#557 Added conditions for video not available message for Odia
  public/locales/en/translation.json
  public/locales/hi/translation.json
  src/components/video/Video.js
Labels: enhancement, SP6

#562 Added the list of features and what's new on Vachan online#523
  public/locales/en/translation.json
  public/locales/hi/translation.json
  src/components/landing/FeaturesList.js
  src/components/landing/Landing.js
  src/components/landing/WhatsNew.js
Labels: enhancement, SP6
